version: '3.8'

services:
  db:
    image: mysql:debian
    env_file: .env
    ports:
      - 3307:3306

  migration:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/3306; do sleep; done; flask db upgrade'
    volumes:
      - .:/code
    depends_on:
      - db
  
  web:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/3306; do sleep; done; flask run --host=0.0.0.0 --port=5000'
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    depends_on:
      - db
      - migration
